### ISSUE TITLE
hardcoded base topic

### ISSUE THREAD

**Issue by aschor** [jneilliii/OctoPrint-MQTTSubscribe#15]
Hi,

in the code, the base topic is hardcoded as example : 
self.mqtt_subscribe("**octoprint**/plugins/mqttsubscribe/" + topic["topic"], self._on_mqtt_subscription) ....etc

And as such, id does not honor (respect) the base topic of "MQTT plugin", which is unfortunate if you happen to have 2 or more printers, you don't want BOTH to execute a command that only one is supposed to execute ...

**Comment by jneilliii** [comment]
I think this issue is already resolved in the upcoming release.

https://github.com/jneilliii/OctoPrint-MQTTSubscribe/tree/0.1.2
