### ISSUE TITLE
ReferenceError: selected_topic is not defined

### ISSUE THREAD

**Issue by W-Floyd** [jneilliii/OctoPrint-MQTTSubscribe#16]
I can't seem to be able to add any topic, console shows `ReferenceError: selected_topic is not defined`

**Comment by W-Floyd** [comment]
For what it's worth, I'm getting by right now by adding commands on the previous release, then upgrading to the newer release to use them.

**Comment by jneilliii** [comment]
About to release new version that fixes this issue, thanks for reporting.

**Comment by W-Floyd** [comment]
Works great, thanks for such a quick fix!
