### ISSUE TITLE
Cant publish a command

### ISSUE THREAD

**Issue by AJErazzor** [jneilliii/OctoPrint-MQTTSubscribe#18]
I am using MQTT.fx to test this but cannot work out what to do?  this isnt really an issue but not sure where else to ask.
Ive set up the connect and disconnect topics and send connect or disconnect command but it doesnt do anything and im not sure what to do with the API key?
Can you expand the documentation and perhaps an example start to finish to help?

**Comment by jneilliii** [comment]
The MQTT topics were separated from the API so you can use pretty much anything now for topics.

![image](https://user-images.githubusercontent.com/5249455/85292265-a3bf2400-b469-11ea-8d0a-924c9aae776e.png)

Then post a message to `myprinter/connect` and it will run the API command configured in settings.
