### ISSUE TITLE
receiving No JSON object could be decoded

### ISSUE THREAD

**Issue by dannieboiz** [jneilliii/OctoPrint-MQTTSubscribe#19]
I'm using homeseer to try to automatically connect the printer upon power on. In the event, the topic is "octoprint/ender3" the message/payload is "connect" 

Seems the message is being received by octoprint but it's throwing an error "No JSON object could be decoded"

**Comment by jneilliii** [comment]
Your message payload should match the requirements of the REST API that you are calling. The specific task you are trying to achieve is documented on the readme actually, in the screenshot.

![image](https://user-images.githubusercontent.com/5249455/89453514-64a11580-d72d-11ea-835c-05a5aad8d0b7.png)

**Comment by dannieboiz** [comment]
That solves my problem. THANKS YOU!!! It can no autoconnect.
