### ISSUE TITLE
HowTo get the Value out of MQTT message?

### ISSUE THREAD

**Issue by nicedevil007** [jneilliii/OctoPrint-MQTTSubscribe#21]
Hey all,

I'm bit new to use this API/MQTT thing for octoprint right now.
I use node-red with MQTT eclipse as my broker to create all my MQTT messages.

My aim is to send a message via Node-RED over MQTT with a command and value that should be used in Octoprint.
So an example can be:

```
{
   "command":"target",
   "targets":{
      "tool0":200
   }
}
```

How should I configure this plugin to dynamical extract the 200 out of this message? I want to set it inside Node-RED to be able to preheat for ABS/PLA and so on with different hotend temperatures?

This here will fix it to only 200°C

![image](https://user-images.githubusercontent.com/17103076/90951598-7f2cfb80-e45c-11ea-8bbe-150c0195ad87.png)

**Comment by jneilliii** [comment]
If I understand what you are trying to achieve correctly I believe the following is what you are looking for.

topic=`printer/nozzlePLA`
JSONPath Extract=`$.temp`
REST API=`/api/printer/tool`
REST Parameters=`{"command" : "target","targets":{"tool0":\1}`

Then the message you publish from Node-Red to the topic `printer/nozzlePLA` would be `{"temp" : 200}`

**Comment by nicedevil007** [comment]
That was exactly what I tried to achieve 👍 Thank you very much!

BTW: is there an easy simple way to load the latest file into the printer over MQTT? I only saw things about the filelist of folders.

**Comment by jneilliii** [comment]
Unfortunately I do not think there is an option for that in the API. You have to know the filename to be able to select it with the option to start printing it.

**Comment by nicedevil007** [comment]
First, thank you again for your awesome work! may I reopen this here?
I was able to get this done for my preheatbutton for hotend/bed.

Now I'm struggling with multiple things in one command:
![image](https://user-images.githubusercontent.com/17103076/90973172-ba443300-e51f-11ea-866a-7d5a1e4582e2.png)

That is what I sent to octoprint by node-red over MQTT:
![image](https://user-images.githubusercontent.com/17103076/90973177-c7f9b880-e51f-11ea-9582-ac089a4e7426.png)

That is the error:
![image](https://user-images.githubusercontent.com/17103076/90973182-d516a780-e51f-11ea-8c52-455e74dd48a0.png)

**Comment by jneilliii** [comment]
I'd have to ask @mdjurfeldt for a little assistance on this one. He/She wrote the JSONPath extraction code and the only example I've seen was with the 2 parameters, but I would assume it should work with more than that. I wonder if you might need to have the numbers in your msg.payload object as strings (quoted) instead of numbers? Did the previous extraction work as expected with a number versus string?

**Comment by nicedevil007** [comment]
I think they have to be numbers, that's what Octoprint API is telling me about it:

![image](https://user-images.githubusercontent.com/17103076/90973464-96362100-e522-11ea-9f05-ef4ebabc0d5b.png)

**Comment by nicedevil007** [comment]
What I figured out right now is, that it only accept the first value!
The 2nd one won't be extracted and used.

**Comment by mdjurfeldt** [comment]
Hi @jneilliii and @nicedevil007,

The matching is done by the jsonpath_rw library. Given the jsonpath extraction pattern, it gives a set of matches and this set is then coupled to \1, \2, etc by OctoPrint-MQTTSubscribe.

If I give jsonpath_rw the extract pattern you use ($.x|$.y|$.z|$.speed) it results in three matches, all having the speed as value. I'm sure that we can understand why by reading the jsonpath_rw documentation. I don't have time to do that now, but it doesn't seem to be a good idea to mention root ($) multiple times.

I instead gave it the pattern $.(x|y|z|speed) which resulted in the four matches that we want.

Try this out, and I think it will resolve your issue!

@jneilliii: I will look at the other issue about string quotes ASAP.

Best regards,
Mikael

**Comment by jneilliii** [comment]
@mdjurfeldt I'm not sure there is an issue relative to string quotes, was just recommending it as a possible option. Thanks for the example of doing the multiple parameters. I hope that works out. I was going off of the example we discussed in the issue [here](https://github.com/jneilliii/OctoPrint-MQTTSubscribe/issues/7#issuecomment-582166178).

**Comment by jneilliii** [comment]
And thanks for the quick reply @mdjurfeldt much appreciated.

**Comment by mdjurfeldt** [comment]
Ah, of course! It's about the precedence of the operators:

If you do:

($.x)|($.y)|($.z)|($.speed)

this version of the old pattern will work as intended.

**Comment by mdjurfeldt** [comment]
But in this case x|y|z|speed is also fine.

(@jneilliii: I read your latest responses first now. Yes, if you look at the example we discussed you'll see that we had the parentheses there to get the right association of operators.)

**Comment by jneilliii** [comment]
I had just edited that post to match the above discussion.

**Comment by jneilliii** [comment]
> But in this case x|y|z|speed is also fine.

Would there be a scenario where this doesn't work? It seems this is a much simpler approach and probably more easily understood by end users.

**Comment by nicedevil007** [comment]
Thank you for now, I guess it will work, can't test right now, late here :)

Will report back tomorrow.

Could you also take a look at the the other issue pls? That where I want to extract the location and file name and insert it as the REST API part of this plugin?
Then I should be able to create an interface that could run most of the octoprint parts inside nodered, and then Alexa can be connected to it with my own Skill 🤩

**Comment by nicedevil007** [comment]
> 
> 
> Hi @jneilliii and @nicedevil007,
> 
> The matching is done by the jsonpath_rw library. Given the jsonpath extraction pattern, it gives a set of matches and this set is then coupled to \1, \2, etc by OctoPrint-MQTTSubscribe.
> 
> If I give jsonpath_rw the extract pattern you use ($.x|$.y|$.z|$.speed) it results in three matches, all having the speed as value. I'm sure that we can understand why by reading the jsonpath_rw documentation. I don't have time to do that now, but it doesn't seem to be a good idea to mention root ($) multiple times.
> 
> I instead gave it the pattern $.(x|y|z|speed) which resulted in the four matches that we want.
> 
> Try this out, and I think it will resolve your issue!
> 
> @jneilliii: I will look at the other issue about string quotes ASAP.
> 
> Best regards,
> Mikael

That is working like a charm 👍
