### ISSUE TITLE
Select File > dynamical change REST API on given MQTT Values

### ISSUE THREAD

**Issue by nicedevil007** [jneilliii/OctoPrint-MQTTSubscribe#22]
Hey @jneilliii,

it's me again. Just want to make a new issue to keep things clear and other guys can find a proper solution on their search ;)

I managed to get the actual files loaded on Octoprint. Then I was able to sort this array by it's date and then I know that the first object in the array is the latest file I can print.

Now I headed to the Octoprint API.

![image](https://user-images.githubusercontent.com/17103076/90976945-d1941800-e541-11ea-9db6-2a160baa02a7.png)

Here you can see we don't have to change the issued command. We only have to change the REST API string. So how can we change the REST API string in your plugin with values provided my a MQTT message?

**Comment by jneilliii** [comment]
Sorry for the late response @nicedevil007 I missed this issue. I see your point. We need a way to parameterize the API command as a separate option/options. It would make sense to follow the same JSONPath extraction method already in use for the REST parameters, if it wasn't already done that way already. I'll have to review the code again and see, I don't think it is.

**Comment by jneilliii** [comment]
So changes I was working on for #20 has resulted in a quicker implementation of this request. It requires some tweaking to your previous REST Parameters, replacing the `\#` tokens with `{#}` tokens instead. One other adjustment is that the tokens are 0 based instead of starting at 1, ie `\1` becomes `{0}` and `\2` becomes `{1}`, etc. You can then use those same tokens in the REST API field. 

For your specific use case it would be like this for example.

![image](https://user-images.githubusercontent.com/5249455/91651790-e9e2c600-ea5e-11ea-8ef7-0f1bb982362d.png)

And submit the message below to the topic `printer/ender3/file` would select the file `20mm_cube_0.2mm_PLA_MK3S_58m.gcode` and automatically start printing it (assuming it can).

```
{"location":"local","path":"20mm_cube_0.2mm_PLA_MK3S_58m.gcode","autoprint":"true"}
```

I'm going to try to tweak the upgrade process and automatically adjust the tokens upon install, but if you want to go ahead and test it out, you can install by copying/pasting the URL below into plugin manager > Get More > ...fromURL and click Install.

```
https://github.com/jneilliii/OctoPrint-MQTTSubscribe/archive/0.1.5.zip
```

**Comment by nicedevil007** [comment]
@jneilliii first of all, THANK YOU! with those changes we should be able to reduce the entries in your MQTT Sub plugin. Now we should not need an entry for everything we just try to subscribe 👍 

what I don't understand in your given screenshot and possible msg.payload: You didn't enter the location/path/autoprint to in the REST Parameters section. In this case it will just extract the object "location/path/autoprint" without those "\1, \2" etc..?

Going to test now!

EDIT: Oh and why you reference to {0} and {1} and use {2}in Parameters? Can't get the point now :/

EDIT2: Ok think I got it now... Now we have to change all old "\1" etc. to new naming scheme {0}....{n}

![image](https://user-images.githubusercontent.com/17103076/91653134-339ed100-ea9e-11ea-8b00-4e8a2767d09e.png)

**Comment by jneilliii** [comment]
> EDIT2: Ok think I got it now... Now we have to change all old "\1" etc. to new naming scheme {0}....{n}

Correct, that's what I tried to explain before.

**Comment by nicedevil007** [comment]
Was understanding it in that way that we have to use `{0}` for all REST API fields and `\1` for all normal REST Parameters, but now it should be clear!

I'm rushing through node-red now to fix everything to new naming scheme and then try to reduce all entries!

.... just because it is the last thing we can't change right now...

post/get ? :P

**Comment by jneilliii** [comment]
That I'd prefer to leave as is I think. If you need to control that you might as well being doing a full REST API implementation in the first place. Doesn't Node Red support API calls on its own?

**Comment by nicedevil007** [comment]
> That I'd prefer to leave as is I think. If you need to control that you might as well being doing a full REST API implementation in the first place. Doesn't Node Red support API calls on its own?

it does but I like it more doing stuff over MQTT... maybe I have to dig into it a bit more. 

For now I'm trying this:
![image](https://user-images.githubusercontent.com/17103076/91664265-55c03f80-eaee-11ea-99a9-1055acebb851.png)

My msg.payload I sent to this topic is this:
![image](https://user-images.githubusercontent.com/17103076/91664292-725c7780-eaee-11ea-8454-5a3a87300c94.png)

A blue "success" message is shown on Octoprint but it won't heat up the bed. I already tryed to don't send "empty" values but then it tells me an error because it seems to need all those variables.

So are you able to let your plugin check if the sent value is empty or not? I mean not "0" but empty "". If it is empty then it shouldn't take care of it. If that isn't possible we are back at this point where we have to create seperate entrys for each command we would like to use in octoprint. Not a huge dealbreaker but bit more to do there.

**Comment by jneilliii** [comment]
Good point, empty values would still get passed through I think, which would probably cause errors. Look at what is returned in the `printer/test/response` topic to see if the API is complaining. The amount of generalization you're doing is an interesting concept, but again, at this point you might as well be using the API directly.

**Comment by jneilliii** [comment]
you may also want to try double quoting your `60`, I noticed that when doing to the true option in my example above it wouldn't work until I did that for some reason.

**Comment by jneilliii** [comment]
I did just figure out that you will want to add double quotes around your tokens, otherwise the json object isn't parsed properly.

```
{
"command":"{2}",
"{3}":"{4}",
"{5}":"{6}",
"{7}":"{8}",
"{9}":"{10}"
}
```

but it's getting converted to with the example above.

```
{"command":"target",
"target":"60",
"":"",
"":"",
"":""}
```

so one way to get around that would be to have a topic for each of the number of parameters you'll be sending possibly? Like `printer/test/1`, `printer/test/2`, etc.

**Comment by jneilliii** [comment]
Looks like the command is getting through that way, but there is an error about the number being a string, so this might be more complicated than I though. A number is able to be sent, but yout REST parameters would have to know which are numbers and which are string and not quote the token for numbers, which complicates this even further.

**Comment by nicedevil007** [comment]
mhhh so I'm at the starting with my "generalization" where I have to create multiple entries in your plugin's setting inside of node-red. My dream was to create just one topic there where I send every msg I like to control the printer.

With that state we get absolutly free! We create everything what we want inside the backend like node-red.

So as I told you, it is good as it is right now, because we can do almost everything with it.

**Comment by nicedevil007** [comment]
> Looks like the command is getting through that way, but there is an error about the number being a string, so this might be more complicated than I though. A number is able to be sent, but yout REST parameters would have to know which are numbers and which are string and not quote the token for numbers, which complicates this even further.

Isn't there a possibility to check if the input is a number or a string? In node-red I have possibilities to check if it is one or an other.

**Comment by jneilliii** [comment]
There is a way to do that with the python format tokens, but currently my curly bracket escaping would probably break it. I did just test this and it works.

```
{
"command":"{2}",
"{3}":{4},
"{5}":"{6}",
"{7}":"{8}",
"{9}":"{10}"
}
```

**Comment by nicedevil007** [comment]
ok let me try this as well :)

thank you for this awesome support!

**Comment by nicedevil007** [comment]
tested but don't work?

![image](https://user-images.githubusercontent.com/17103076/91665234-40e6aa80-eaf4-11ea-9ef6-a8516a48f8ed.png)
the upper one is the msg I have sent to the printer
the lower one is what I get out of a mqtt IN node.

![image](https://user-images.githubusercontent.com/17103076/91665247-6c699500-eaf4-11ea-8fa1-d075f05f0c73.png)

**Comment by jneilliii** [comment]
I wonder if you could get rid of the double quotes in the REST parameters, and then pass those as text when necessary from the Node-Red side? All the json property names would need to be quoted, so might as well do that on the REST parameters side.

**Comment by jneilliii** [comment]
You missed that I took the quotes away from `{4}`

**Comment by nicedevil007** [comment]
ah ok... but then it is not usefull for general usecase. As you already wrote... we have to figure out how to get rid of those "" around the parameters.

The Node-RED part send a string in "" and a number without.

**Comment by jneilliii** [comment]
Yeah, that's why I was thinking of doing it like this.

```
{
"command":{2},
"{3}":{4},
"{5}":{6},
"{7}":{8},
"{9}":{10}
}
```

**Comment by nicedevil007** [comment]
Have an other idea that can make things a lot easier if it works.

What if we create the whole command inside node-red?

**Comment by jneilliii** [comment]
You could definitely send the whole payload and make the REST parameter.

```
{2}
```

**Comment by jneilliii** [comment]
in theory

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/91665368-63c58e80-eaf5-11ea-9685-492e0e28cf4d.png)

like this yeah?

**Comment by jneilliii** [comment]
if you subscribe to `printer/test/response` you'll see what the REST parameters get converted to in the data property.

**Comment by jneilliii** [comment]
Yes, like your example above.

**Comment by nicedevil007** [comment]
> if you subscribe to `printer/test/response` you'll see what the REST parameters get converted to in the data property.

I subscribed to everything printer/# and there isn't a response

![image](https://user-images.githubusercontent.com/17103076/91665391-82c42080-eaf5-11ea-8b36-f049026aeaa9.png)

**Comment by jneilliii** [comment]
let me test real quick

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/91665447-ee0df280-eaf5-11ea-94bb-6b4ec5c50765.png)

like this?

With this i get a blue message but nothing happens:

![image](https://user-images.githubusercontent.com/17103076/91665470-201f5480-eaf6-11ea-9cbd-88a6530eb155.png)

**Comment by jneilliii** [comment]
Yeah it's complaining about the URL being posted to. If you remove the third token in the REST API path it will probably work.

**Comment by nicedevil007** [comment]
> Yeah it's complaining about the URL being posted to. If you remove the third token in the REST API path it will probably work.

nope it is not :/
![image](https://user-images.githubusercontent.com/17103076/91665537-9754e880-eaf6-11ea-9a32-f76c34794ef4.png)

![image](https://user-images.githubusercontent.com/17103076/91665543-a50a6e00-eaf6-11ea-9a30-045814414b58.png)

**Comment by jneilliii** [comment]
That seems to complain about JSON decoding though.

**Comment by jneilliii** [comment]
I'm going to have to think about this for a bit. May require additional work.

**Comment by nicedevil007** [comment]
![image](https://user-images.githubusercontent.com/17103076/91665577-e3079200-eaf6-11ea-8759-09c24a4c2dad.png)

**Comment by nicedevil007** [comment]
Ok no problem :) Getting this done with the last example would be the best solution.

**Comment by jneilliii** [comment]
Yeah, that's the error I was seeing. I'm sure it's something simple like converting the object to a string or something, just have to work through the lines to see what it's interpreting as it's going through the token replacement process.

**Comment by jneilliii** [comment]
Ok, figured out that this works for msg payload...so my assumption is probably correct about converting from an object to string.

```
{"a":"printer","b":"bed","c":"","d":"{\"command\":\"target\",\"target\":0}"}
```

**Comment by nicedevil007** [comment]
Tryed it and still not working.

that is my input

`{"apiA":"printer","apiB":"bed","apiC":"","command":"{\"command\":\"target\",\"target\":60}"}`

and that is the response:

`{ "status" : 404, "response" : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>404 Not Found</title><h1>Not Found</h1><p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p> "data" : {"command":"target","target":60} }`

EDIT: it is working without the empty 3rd variable for the API call.
The thing we did on the REST Parameters with just one {2} there should work on the REST API line as well right? :)

EDIT2: yeah it is working like a charm... :D now we only need 1 topic for GET and one topic for post unless you change it at :P

![image](https://user-images.githubusercontent.com/17103076/91668562-db071c80-eb0d-11ea-83fa-c3e8b29e7ab3.png)

And here is an example of the input (msg.payload sent by node-red over MQTT):

```
{
    "api": "printer/bed",
    "command": "{\"command\":\"target\",\"target\":60}"
}
```

**Comment by jneilliii** [comment]
Cool, nice idea by streamlining the REST API and send it in one variable. Sorry the rest of the day got away from me, but I think I can fix the issue with the command object and not have to escape the quotes. What's happening is it's loading into the plugin with single quote marks for strings instead of double quotes, and when it tries to convert that string to JSON it isn't happy. By doing a global replacement of the single quote character with a double quote on that string I think I can make the embedded object work more naturally. Will have to do some additional testing with a string that includes a single quote/apostrophe to see what happens in that case, but we'll get it worked out.

**Comment by nicedevil007** [comment]
> Cool, nice idea by streamlining the REST API and send it in one variable. Sorry the rest of the day got away from me, but I think I can fix the issue with the command object and not have to escape the quotes. What's happening is it's loading into the plugin with single quote marks for strings instead of double quotes, and when it tries to convert that string to JSON it isn't happy. By doing a global replacement of the single quote character with a double quote on that string I think I can make the embedded object work more naturally. Will have to do some additional testing with a string that includes a single quote/apostrophe to see what happens in that case, but we'll get it worked out.

That would be even more awesome. Looks a bit "weird" right now but it is working.

Here a screenshot out of my node-red.

![image](https://user-images.githubusercontent.com/17103076/91742518-ad29e280-ebb6-11ea-8987-63bb2e35fa8a.png)

**Comment by nicedevil007** [comment]
Now I have a special problem that seems ok from the message but it is not working.
Heating the bed with the lower part of this is working as expected:

```
var p=msg.payload,
    h=flow.get('hotend')||200,
    b=flow.get('bed')||60,
    ht=flow.get('heating');
    topic='printer/post',
    c='{\"command\":\"target\",\"';

if (!ht) {h=0;b=0;}

if (p) {
    api='printer/tool';
    s=c+'targets\":{\"tool0\":'+h;
    return {payload: {api, command: s+"}"}, topic}
} else {
    api='printer/bed';
    s=c+'target\":'+b;
    return {payload: {api, command: s+"}"}, topic}
}
```

That is the response for the part after "if (p)"
```
{ "status" : 400, "response" : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>400 Bad Request</title><h1>Bad Request</h1><p>The browser (or proxy) sent a request that this server could not understand.</p> "data" : {"command":"target","targets":{"tool0":185} }
```

The response for the bed looks like this with the message I created from my function above:

`{ "status" : 204, "response" :  "data" : {"command":"target","target":70} }`

**Comment by jneilliii** [comment]
Should `s=c+'targets\":{\"tool0\":'+h;` be `s=c+'target\":{\"tool0\":'+h;`?

**Comment by jneilliii** [comment]
Never mind, I see the tool API is plural.

**Comment by jneilliii** [comment]
But you might be missing a `}` at the end?

**Comment by nicedevil007** [comment]
> But you might be missing a `}` at the end?

that could be... will test tomorrow, printer is working right now... yeah working not printing :D:D:D
