### ISSUE TITLE
Single '}' encountered in format string

### ISSUE THREAD

**Issue by AJErazzor** [jneilliii/OctoPrint-MQTTSubscribe#25]
after an upgrade I now get the error
Single '}' encountered in format string
This appears when sending a job from prusaslicer
no other settings changed between versions

**Comment by jneilliii** [comment]
can you provide the full error log so I can see what line that is happening at? Also, please share a screenshot of your settings.

**Comment by AJErazzor** [comment]
I hope it’s ok to ask where I get the log from 

Thanks
Andrew

**Comment by jneilliii** [comment]
Of course, go to OctoPrint's settings and in the logging section download the file octoprint.log. You can drag it into a comment here on github to upload and share. Feel free to just look in that file (text based) for the specific error potentially. Just need to get the full error message to be able to find the line that's choking up. It would also be helpful to see your settings you've configured in the plugin.

**Comment by AJErazzor** [comment]
I cant see the error in there but I forced the error to appear and can see that gcode loading
[octoprint small.log](https://github.com/jneilliii/OctoPrint-MQTTSubscribe/files/5432213/octoprint.small.log)

**Comment by AJErazzor** [comment]
![mqtterror](https://user-images.githubusercontent.com/5545511/97063790-4c80ba00-15e9-11eb-9d51-98a0e2c79596.PNG)
![mqttsettings](https://user-images.githubusercontent.com/5545511/97063792-4db1e700-15e9-11eb-8f6a-2b6160feb6d1.PNG)

**Comment by jneilliii** [comment]
Can you try changing the REST Parameters for the connection to `{"command":{0}}`

**Comment by AJErazzor** [comment]
Sorry, didnt make a difference.  I have confirmed it only happens on the connection command though

**Comment by jneilliii** [comment]
Can you please share the full settings of that command, so I can see how you have the inputs configured?

**Comment by AJErazzor** [comment]
Calling from openhab (home automation)

    var url = "http://<octoprintIP>/api/files/local/" + OctoprintFileUploadPath.state + "?apikey=<apikey>"
    var contenttype = "application/json"
    var POSTrequest = '{"command":"select"}'
    var output = sendHttpPostRequest(url, contenttype, POSTrequest)

**Comment by AJErazzor** [comment]
I am sending from prusa slicer (2.3 alpha 2) is this what you mean?

**Comment by jneilliii** [comment]
No I mean can you share a screenshot of that one connection command by pressing the edit button and showing the pop-up editor. I want to try and re-create exactly what you have configured.

**Comment by jneilliii** [comment]
Ok, I figured out what's going on. Due to the switch to python formatting, the json object being sent to the api currently has to have some whitespace in it. So if you update your connect topic to this it should work again.

![image](https://user-images.githubusercontent.com/5249455/97206199-c7cfa080-178e-11eb-8e88-03951abb7cf1.png)

Notice the space after the opening `{` and before the closing `}`. So it should be `{ "command":{0} }` until I have time to figure out a way to fix this.

**Comment by AJErazzor** [comment]
OK - confirmed the above removes the error, however, the command itself doesnt fire
![image](https://user-images.githubusercontent.com/5545511/97244181-d8901d00-1847-11eb-963a-aeaa90313a7b.png)

Log shows:
2020-10-27 11:26:00,838 - tornado.access - WARNING - 400 POST /api/connection (::1) 18.12ms

any ideas?

**Comment by jneilliii** [comment]
can you share a screenshot of your setting in the plugin and what you're sending to the topic as a message? For the example I gave above I just send the word `connect` or `disconnect` and it will handle both.

**Comment by AJErazzor** [comment]
![image](https://user-images.githubusercontent.com/5545511/97246388-25c2bd80-184d-11eb-8ffd-6594f1aadd75.png)
![image](https://user-images.githubusercontent.com/5545511/97246419-35420680-184d-11eb-8f39-7765cbf9df21.png)
this is from Openhab where I have an on/off switch

here is the screenshot from octobrint
![image](https://user-images.githubusercontent.com/5545511/97247961-9f0fdf80-1850-11eb-9059-10d5e1d63732.png)

**Comment by AJErazzor** [comment]
OK I got it working if I remove the JSONPATH and just send connect or disconnect - I think issue 7 talks about the /1 syntax that I was using before - perhaps that has been deprecated in this release?
Turns out I didnt need it anyway but not sure if others are relying on this functionality?

**Comment by jneilliii** [comment]
> I think issue 7 talks about the /1 syntax that I was using before - perhaps that has been deprecated in this release?

Yeah, that was one of the differences made in this latest release, switching, in preference of python string formatting nomenclature `{0}`.  That being said what you had before should have worked with this new format with the $.usbconnect path in place because you were sending that json message formatted that way. I'll do some more debugging as I work out the space issue and see why that wasn't working as expected.

**Comment by jneilliii** [comment]
The meat of the change was discussed in #22 with a couple of different detailed examples.

**Comment by AJErazzor** [comment]
OK no probs thanks
