### ISSUE TITLE
Turning lights on/off not working

### ISSUE THREAD

**Issue by thermoscookies** [jneilliii/OctoPrint-MQTTSubscribe#27]
I have MQTT and MQTT Subscribe setup and appears to be configured correctly.

Here is my command:
![image](https://user-images.githubusercontent.com/22629136/100919806-24f5fa80-348f-11eb-870f-e420d9a4298f.png)

I am able to make the mqtt call successfully and the mqtt command makes the api call as show in the log:
`2020-12-02 19:12:21,298 - tornado.access - INFO - 200 POST /api/printer/command (127.0.0.1) 21.82ms`

but the lights don't turn on or off. Could there be an issue because of the space between the M42 command and the S255 value? I'm not sure what to check next or where to look.

EDIT: Forget to mention that the api call works correctly when I do it via curl:
`curl -X POST -H "Content-Type: application/json" -H "X-Api-Key: my_api_key" -d '{"command": "M42 S255"}'  http://192.168.10.65/api/printer/command`

**Comment by jneilliii** [comment]
I think you might be running into a formatting issue with the json string and how the plugin reads it. I haven't had a chance to try and fix it yet, but if you make your rest paramaters like this I think it will work.

```
{ "command": "M42 S255" }
```

**Comment by thermoscookies** [comment]
> I think you might be running into a formatting issue with the json string and how the plugin reads it. I haven't had a chance to try and fix it yet, but if you make your rest paramaters like this I think it will work.
> 
> ```
> { "command": "M42 S255" }
> ```

That fixed it, thank you for your help!

**Comment by jneilliii** [comment]
Newer version should allow for the formatting issues in json and not require the whitespace anymore.
