### ISSUE TITLE
2 subscriptions on the same topic & different parameters : triggers all actions

### ISSUE THREAD

**Issue by aschor** [jneilliii/OctoPrint-MQTTSubscribe#28]
Hi,

I have to raise again an old issue I already had raised before : https://github.com/jneilliii/OctoPrint-MQTTSubscribe/issues/4#issuecomment-557891600

I did upgrade octoprint, mqtt and mqtt subscribe. And now, my subscriptions don't work anymore. Or to be exact, the bug has re-appeared. I fire one and only one commant through mqtt, and 2 actions match and trigger opposite actions :

![image](https://user-images.githubusercontent.com/16648585/103481511-c13b5600-4ddb-11eb-8779-1382cf6da4d7.png)

and this is what happens : 
![image](https://user-images.githubusercontent.com/16648585/103481532-e62fc900-4ddb-11eb-928c-725c64658c75.png)
![image](https://user-images.githubusercontent.com/16648585/103481541-f9429900-4ddb-11eb-8a5e-8540e65c0a4b.png)

with those subscriptions :
![image](https://user-images.githubusercontent.com/16648585/103481554-0d869600-4ddc-11eb-8f31-0969ff104ee1.png)

could you please investigate ? this is breaking my setup right now, I cannot swith my leds on or off ... and I had a third command subscribed to /api/printer/command, say "power off printer" ......... then I guess that switching the lights would poweroff the printer ............... :/ 

I have MQTT Subscribe (0.1.6) installed

fast reading the new code, I think the logic is flawed : only TOPIC is matched everywhere, no matter what the message is, or I am reading it wrong ?

line 133 :
```
		for t in self._settings.get(["topics"]):
			if topic == t["topic"]:
				self._logger.debug("Found match " + t["topic"])
```
where is the subscribed data matched against subscription ?? `topic == t["topic"]`  is **NOT** a match, it's a **PARTIAL** match. It is a match **IF AND ONLY IF** the received data is equal to the subscribed data (REST parameters).

**Comment by jneilliii** [comment]
Because you're using the same mqtt topic path I think you would benefit from the jquery extraction options. Then you send the action in your payload and only have the single subscription.

**Comment by aschor** [comment]
hi @jneilliii 

I'm not sure I understand you. I use the same topic path (octoprint/plugins/mqttsubscribe/printer/command) because, as I understood with previous versions, it is (was ??) the only way to talk to mqttsubscribe plugin, am I wrong here ?

Sure I would benefit from jquery extraction options, I'll look into it thanks. So, as I understand, the logic behind the pluggin has changed somehow.

**Comment by jneilliii** [comment]
The if logic was changed in version 0.1.2 if I remember correctly when the jsonpath expression extraction was introduced.

**Comment by aschor** [comment]
hummm OK.

I read the doc behind the new logic/philosophy, and also the jsonpath extract examples .......... and I couldn't get mything to work with the provided examples........ I always get a "Json malformed" with something like { "command": "my command  Leds\1" } in the rest parameters . Because of the "\1" being INSIDE the string

BUT. Reading the code I foud a hack that works :

![image](https://user-images.githubusercontent.com/16648585/103540529-22c1fa00-4e9a-11eb-8627-375a6eb15c10.png)

Yes, the index here starts at 0 or I get a "tuple index out of range" error.... that is weird, but that works with this simple MQTT message :  { "commande" : "OFF" }
and Jsonextract : $.(commande)


(this is instructing octoprint to instruct klipper ....  to command Octoprint action commmand plugins. If there is a better way I'm all ears)

do we close this issue, or does it stay open, if you want to implement a working "\1 \2" syntax inside strings in rest parameters ?

**Comment by jneilliii** [comment]
My bad, I forgot to mention after the jsonpath extraction was added the replacements got switched over to use python token formatting instead of the \1 \2 formatting, so what you figured out is the proper approach. I will leave this ticket open to remind me to update the docs to make this a little more clear. Sorry again for all the headaches.

**Comment by Arquiteto** [comment]
Okay, so what is the correct way to parse commands now? I'm trying to create MQTT switch in HA. Unfortuantely HA doesn't support sending different topics to 1 switch, so I need to use payload with for example "connect" and "disconnect" commands, and I have no idea how to make it work with parsing JSON.

**Comment by jneilliii** [comment]
If I'm not mistaken you should be able to use a REST parameters below and then your payload is either `connect` or `disconnect`.
```
{ "command":"{0}" }
```

**Comment by Arquiteto** [comment]
@jneilliii 

I think I'm doing this right, but unfortunatelly it doesn't work.

Here's my MQTT Subscribe config
![image](https://user-images.githubusercontent.com/33292677/108636896-5d9ee200-7488-11eb-96d5-c6d0e00de921.png)

And my MQTT message:
![image](https://user-images.githubusercontent.com/33292677/108636892-57106a80-7488-11eb-9aa4-7459ddb320fc.png)

**Comment by jneilliii** [comment]
change your payload to raw and send just the text `connect` or `disconnect` and change your JSONPath extract to be blank.

**Comment by Arquiteto** [comment]
This doesn't work as well unfortunatelly :(

**Comment by jneilliii** [comment]
I have confirmed that this works with just sending a payload of `connect` or `disconnect` to the configured topic. Once you've made the change, restart OctoPrint just to rule out any possible issues with subscriptions.

![image](https://user-images.githubusercontent.com/5249455/108869835-94c6dd80-75c5-11eb-80f4-0572f0d6f603.png)

**Comment by Arquiteto** [comment]
Okay, thank you very much for help. The problem was with the quotation marks around {0}. Without them it works.
