### ISSUE TITLE
tornado.access - WARNING - 403 GET /api/connection (127.0.0.1) 10.40ms

### ISSUE THREAD

**Issue by grosj** [jneilliii/OctoPrint-MQTTSubscribe#29]
Hello,

I'm using OctoPrint in a docker container with this plugin.

Now I'm sending a MQTT-Message
`printer/connect
{"command":"connect"}
`
or 

`printer/connect
connect
`

and both I get the following response:
`printer/connect/response
{ "status" : 403, "response" : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>
 }`

In the log-file I found this entry:
`2021-01-04 19:04:49,442 - octoprint.plugins.mqttsubscribe - DEBUG - Received from printer/connect|b'{"command":"connect"}'
2021-01-04 19:04:49,444 - octoprint.plugins.mqttsubscribe - DEBUG - Found match printer/connect
2021-01-04 19:04:49,496 - tornado.access - WARNING - 403 GET /api/connection (127.0.0.1) 10.40ms
`

This is my configuration:
<img width="363" alt="2021-01-04 19_20_04-OctoPrint" src="https://user-images.githubusercontent.com/56541936/103566340-25384a00-4ec2-11eb-810c-855b606272f7.png">

I'm confused what's wrong!

Best Regards,
Marco

**Comment by jneilliii** [comment]
403 forbidden make me think you didn't go through the process of setting up your API key in the plugin's settings?

![image](https://user-images.githubusercontent.com/5249455/103569852-07ed8680-4e96-11eb-888a-9a97f92a696d.png)

Press the `+` sign there and then allow on the pop up that shows, and then save your settings.

**Comment by grosj** [comment]
Thank you for your fast answer.
I have setting up an API key.
Now I get the following response
`{ "status" : 200, "response" : ...}`
But the Web-Frontend show the status the printer is not connected and "offline".

When I call the API per REST the connection will established and in the Web-Frontend shows online/ready.

**Comment by jneilliii** [comment]
oh, small little formatting issue with your REST parameters until I have time to try and fix it. Make the REST parameter as follows and it should work. The plugin needs whitespace between the curly brackets and quotation marks. Once you change that it should work as expected I think.

```
{ "command": "connect" }
```

**Comment by grosj** [comment]
Thank you for the answer.
I have change the configuration, but it don't work ...
![image](https://user-images.githubusercontent.com/56541936/103679725-7fe6aa00-4f85-11eb-9d7b-26f0040c7b26.png)

**Comment by jneilliii** [comment]
you need to use a `post` type for sending commands and performing actions.

**Comment by jneilliii** [comment]
notice how here in the docs, the front of the part highlighted in blue says POST.

https://docs.octoprint.org/en/master/api/connection.html#issue-a-connection-command

**Comment by grosj** [comment]
Ohh.... that's it... it runs. I don't see this little thing.

Thank you for your fast support. And sorry for my blindness.

**Comment by ryancasler** [comment]
WHITE SPACE BETWEEN THE CURLY BRACKET AND THE COMMAND?!?!?!   That's all I've been doing wrong?!?  I've been trying to figure this out forever!!!!  A little tip on the main read-me might be nice.  _grumble grumble_ 
🤡 🤪   In all seriousness though, it would be kinda helpful.  Thanks so much for the wonderful plugin!!!   👍

**Comment by jneilliii** [comment]
Yeah, I keep forgetting to put that on the readme, I apologize. Documentation always falls short.

**Comment by jneilliii** [comment]
Hopefully the above commit will help the next guy. Sorry for the headaches @ryancasler
