### ISSUE TITLE
Status code : 400

### ISSUE THREAD

**Issue by yaabaa** [jneilliii/OctoPrint-MQTTSubscribe#3]
Hi, 

I would like to command via mqtt my 3D print with octoprint, for instance this : {"command":"G28"}

I wrote this in payload, with json format in Node Red. 
Mqtt plugin and mqtt subscribe plugin installed and configured.
<img width="742" alt="Capture d’écran 2019-08-11 à 18 40 37" src="https://user-images.githubusercontent.com/53339936/62836860-064f6d00-bc68-11e9-8e10-81bb965f959c.png">

When I send command in node red, a pop up appear in octoprint screen with status code : 400.

Check status code definition [here ](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.1) but can't find solution.

Any idea to help me ?

Thank you,

**Comment by jneilliii** [comment]
Can you post a screenshot of the plugin's settings?

**Comment by jneilliii** [comment]
The Topic should be `printer/command` and the payload is `{"command":"G28"}`.

**Comment by yaabaa** [comment]
Hi, 
Thank you for your quick reply.
I adjust topic as you mentioned, but still doesn't work.

Here some screen about plugin and node red mitt publish ( inject is set to json )

<img width="774" alt="Capture d’écran 2019-08-12 à 18 30 54" src="https://user-images.githubusercontent.com/53339936/62881387-ff8c2d00-bd2f-11e9-9b89-0109dc3ed150.png">
<img width="821" alt="Capture d’écran 2019-08-12 à 18 31 45" src="https://user-images.githubusercontent.com/53339936/62881397-03b84a80-bd30-11e9-954b-cffdc5047716.png">

Thank you a lot for your help !

**Comment by yaabaa** [comment]
Dear Jneilliii, 

I update / reboot my Pi, and it's working now. Perfect for my project.

Thank you a lot for your help and your time to develop this plugin.

Bye,
