### ISSUE TITLE
How do I send the G90 G1 X50 Y50 Z30 F3000 command to the Home Assistant using the MQTT service?

### ISSUE THREAD

**Issue by DivanX10** [jneilliii/OctoPrint-MQTTSubscribe#37]
Installed OctoPrint 1.8.6
Плагин: MQTT Subscribe (0.1.8)

If I send the command G90 G1 X50 Y50 Z30 F3000 through the terminal, then the printer works. How to configure it correctly so that I can send such a command via Home Assistant using the MQTT service?

![image](https://user-images.githubusercontent.com/64090632/205940446-db1e5500-03c8-4875-9272-f47ae0d0e00f.png)

If I send a command to the Home Assistant via MQTT, then it doesn't work
![image](https://user-images.githubusercontent.com/64090632/205940734-0d22939f-ac1b-4413-8e58-ce3357882302.png)
![image](https://user-images.githubusercontent.com/64090632/205941130-03608b62-80bc-4eb0-b905-bca0729418be.png)

I tried it as they wrote [here](https://github.com/jneilliii/OctoPrint-MQTTSubscribe/issues/21#issuecomment-678969385), also does not work

![image](https://user-images.githubusercontent.com/64090632/205940951-bea3b446-0d11-4a3d-b18b-a05b96a817e7.png)
![image](https://user-images.githubusercontent.com/64090632/205941341-1cefd8d7-6a5d-43e7-9c05-b571b1582a53.png)
![2022-12-06_17-05-28](https://user-images.githubusercontent.com/64090632/205942614-69a8c5b4-1f59-4945-a208-132a82ccef84.png)

Marked with a green check mark, it works
![image](https://user-images.githubusercontent.com/64090632/205942009-20506339-cda8-4f2f-bf0d-13152c99537e.png)

For example, roll out the platform to me with the command { "command": "G1 Y200 F3000" }
![image](https://user-images.githubusercontent.com/64090632/205942151-24bb63cb-8d8e-4848-a9f2-38480b5d6875.png)

**Comment by jneilliii** [comment]
well...in this screenshot
![image](https://user-images.githubusercontent.com/5249455/205972229-291c7da3-ecb0-4658-9357-8616d1602f5a.png)
the json extract path parameter doesn't match the payload json you're sending via MQTT. `$.mycommand` should be `$.command` based on the MQTT screenshot that follows as you're sending `{ "command" : "G90..." }`.

**Comment by DivanX10** [comment]
I tried it as you said. Launched, the platform starts to move out and after the octoprint gives an error 
Replacement index 0 out of range for positional args tuple. Maybe it's necessary in some other way? It works through the terminal, but even does not want to subscribe through MQTT

![image](https://user-images.githubusercontent.com/64090632/205997271-5e5001b4-06c1-40ed-ad93-dfbc16333ae7.png)
![image](https://user-images.githubusercontent.com/64090632/205997381-f10888fe-2c68-49b3-ad74-11f2bcaf07c1.png)
![image](https://user-images.githubusercontent.com/64090632/205997219-1cc4de11-db66-40ae-9bcc-310cf073c8ba.png)

Tried [such](https://docs.octoprint.org/en/master/api/printer.html#issue-a-print-head-command) option and also does not work.

```
POST /api/printer/printhead HTTP/1.1
Host: example.com
Content-Type: application/json
X-Api-Key: abcdef...

{
  "command": "jog",
  "x": 10,
  "y": -5,
  "z": 0.02
}
```
![image](https://user-images.githubusercontent.com/64090632/206000122-1bfe2d9e-1c14-4656-ab9a-7010e2853f78.png)
![image](https://user-images.githubusercontent.com/64090632/206000007-174ecbbd-ea7d-4d53-b627-0486e5462d66.png)
![image](https://user-images.githubusercontent.com/64090632/205999982-b18288ae-f416-4f6d-9f72-26e9e2652f02.png)

**Comment by DivanX10** [comment]
The question is relevant. There is no answer how to send a command correctly so that the printer works it correctly

**Comment by DivanX10** [comment]
How can I send several commands so that the printer does not signal after sending the command and the home parking does not stop working? The coordinates of the printer are lost and only complete shutdown and turning on of the printer restore the coordinates and the printer can park.

How to specify commands correctly? { "command": "G91 G0 Y200 F3000 G90" }
G91 (transition to relative coordinates)
G0 Y200 (move by Y)
G90 (return to absolute coordinates)

**Comment by DivanX10** [comment]
I found a curious thing. If I use this plugin [OctoPrint-HomeAssistant](https://github.com/cmroche/OctoPrint-HomeAssistant#send-gcode-from-lovelace ) then the Anycubic Kobra printer perfectly fulfills the command and does not reset the coordinates and does not signal with a sound signal, and if I use the MQTT Subscribe plugin and specify the code `{ "command": "G1 Y200 F3000" }`, then the printer loses coordinates, stops working and a lot it signals multiple times with an audible signal.  The problem comes out in your MQTT Subscribe plugin, which causes an error and the printer stops working at all, only a full reboot brings it to life

```
type: entity-button
name: Level Bed
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: octoPrint/hassControl/commands
    payload: "G29"
```

С плагином OctoPrint-HomeAssistant работает отлично
![image](https://user-images.githubusercontent.com/64090632/209452000-af69a255-c9d2-4f97-8adc-3bd15f2ca775.png)

```
service: mqtt.publish
data:
  topic: octoPrint/hassControl/commands
  payload: "\"G1 Y200 F3000\""

```

**Comment by jneilliii** [comment]
Enable debug logging for the plugin in OctoPrint's logging section and attempt the command then share your log. Need to check for errors.

**Comment by jneilliii** [comment]
This worked for me...

![image](https://user-images.githubusercontent.com/5249455/209452909-5854424e-7cf7-417d-87d1-51952d135833.png)

![image](https://user-images.githubusercontent.com/5249455/209452914-ac2f0864-3833-435e-bb8e-a7d60a49fd66.png)

![image](https://user-images.githubusercontent.com/5249455/209452919-102cae48-84eb-45a1-890e-370c5e816699.png)

**Comment by jneilliii** [comment]
Here's a more advanced example, extracting all the individual bits.

![image](https://user-images.githubusercontent.com/5249455/209452987-abfd6dd0-298f-4be6-bd5d-4a0e28e278b3.png)

![image](https://user-images.githubusercontent.com/5249455/209452990-f222b30c-0197-439f-b39e-88b668e67237.png)

![image](https://user-images.githubusercontent.com/5249455/209452995-d3a2fda4-e523-4da0-bcf9-28134ba69bbe.png)

**Comment by DivanX10** [comment]
> Enable debug logging for the plugin in OctoPrint's logging section and attempt the command then share your log. Need to check for errors.

Thanks. Did I understand you correctly that you need to select octoprint.plugins.mqttsubscribe and error for logging?
![image](https://user-images.githubusercontent.com/64090632/209453192-1b616d79-04aa-4ff3-bd7f-b24ec864c859.png)

**Comment by jneilliii** [comment]
Yeah, but instead of error, change the drop down to debug. Either way, I think my examples above should work for your needs.

**Comment by DivanX10** [comment]
Checked it out. All options have worked, except for one option, if I specify one axis instead of 3 axes. I understand that you need to specify a topic like MQTT. I was surprised at first that you specified the topic `octoPrint`, since I thought that MQTT Subscribe looks at MQTT regardless of the topic `octoPrint`, listens to it, and as it sees its topic, which we specify in the line, it reacts and sends a command to the printer.  And yet, I specified the topic `octoprint`, and the MQTT plugin specified the topic `octoPrint` and apparently, due to the fact that the register check is turned off, hence the heated platform options and nozzles worked on the topic `octoprint`. Therefore, according to your examples, it didn't work for me right away, until I paid attention to which topic you indicated, and as the topic `octoPrint` indicated, it worked.

This working option

**Topic:** `octoPrint/cmd/command`
**JSONPath Extract:** `($.x)|($.y)|($.z)|($.speed)`
**REST API:** `/api/printer/command`
**REST Parameters:** `{"command":"G1 X{0} Y{1} Z{2} F{3}"}`

Starting the service in Home Assistant
```
service: mqtt.publish
data:
  topic: octoPrint/cmd/command
  payload: '{"x":50,"y":50,"z":20,"speed":1000}'
``` 
-------
It does not work for one axis, probably it is not provided. How can this be implemented for one axis or only for two axes?

**Topic:** `octoPrint/cmd/command`
**JSONPath Extract:** `($.y)|($.speed)`
**REST API:** `/api/printer/command`
**REST Parameters:** `{"command":"G1 Y{1} F{3}"}`


Starting the service in Home Assistant
```
service: mqtt.publish
data:
  topic: octoprint/cmd/command
  payload: '{"y":50,"speed":2000}'
```
------

This option also worked

**Topic:** `octoPrint/cmd/command`
**JSONPath Extract:** `$.gcode`
**REST API:** `/api/printer/command`
**REST Parameters:** `{"command":"{0}"}`


Starting the service in Home Assistant
``` 
service: mqtt.publish
data:
  topic: octoPrint/cmd/command
  payload: '{"gcode":"G1 Y50 F3000"}'
``` 
-----

These are working examples
![image](https://user-images.githubusercontent.com/64090632/209453982-024786f0-eab2-44b7-ad31-18728a638332.png)
![image](https://user-images.githubusercontent.com/64090632/209453985-bebe344b-d661-4381-9e9d-a5e2507bdd80.png)
![image](https://user-images.githubusercontent.com/64090632/209453988-433bef71-52d3-4751-814d-083f217112cf.png)
![image](https://user-images.githubusercontent.com/64090632/209453996-6fa7a24f-bd01-479a-9cd5-0cfb2747780c.png)
![image](https://user-images.githubusercontent.com/64090632/209453999-ca35bfef-34be-4ab7-8d06-ca92052ab627.png)

**Comment by DivanX10** [comment]
> Yeah, but instead of error, change the drop down to debug. Either way, I think my examples above should work for your needs.

I have something not writing to the log, although I chose the octoprint.plugins.mqttsubscribe debug mode. How many errors I have surfaced, but there are no entries in the logs
![image](https://user-images.githubusercontent.com/64090632/209454189-b79c5aa5-20b6-408a-9113-a337c265d1d8.png)

**Comment by DivanX10** [comment]
Thank you very much, I'm closing the topic

**Comment by jneilliii** [comment]
the plugin will write it's info into octoprint.log. I've never thought of a way to do optional parameters being sent. not sure if there is a way to do that in the current implementation. would have to experiment a bit. if I convert the plugin to using python f string conversion I might be able to do some more complicated replacements.

**Comment by jneilliii** [comment]
> since I thought that MQTT Subscribe looks at MQTT regardless of the topic `octoPrint`

This is true. It doesn't matter what the topic is. For example in this screenshot, both of these topics do the same thing.

![image](https://user-images.githubusercontent.com/5249455/209457309-08fb5f12-e60d-4abb-b35e-df891405ab7b.png)
