### ISSUE TITLE
Disable "MQTT Command Received for..."

### ISSUE THREAD

**Issue by Dennis650** [jneilliii/OctoPrint-MQTTSubscribe#6]
Hi,

thank you for this great Plugin. I use it with openHab.

I can turn on/off a relay for the PSU via the plugin PSUControl.

Therefore, i also want the state of the relay in OpenHab. Every 30 seconds send a MQTT message. The Response contains the State of the relay. It works great.

For each message (request for the relay status every 30 seconds), a notification is displayed in the webfrontend. Would it be possible to implement that these notifications be switched off by configuration?

Greetings
Dennis

**Comment by jneilliii** [comment]
I'm staging an update now with this option added and several other new features, discussed in issue #7. Updating will probably break some of your OpenHab subscriptions, but may also help you long term.  Upon upgrade, you may want to adjust your MQTT publishing commands and update plugin settings.  Responses have been moved to `<topic>/response` I've tried to account for the conversion in data structure as best I can, but just wanted to give you a heads up.  If you'd like to try it out and test for me that would be great though.  You can install using the URL below in plugin manager.

https://github.com/jneilliii/OctoPrint-MQTTSubscribe/archive/0.1.2.zip
